[theme]
base = "dark"
primaryColor = "#d4af37"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#161411"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
